name: GitHubTraffic
language: Python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: github_data
    required: true
  - name: GH_TOKEN
    inputType: Secret
    description: GitHub token
    defaultValue: GH_TOKEN
    required: true
  - name: GH_REPO
    inputType: FreeText
    description: Quix IO GitHub repo
    defaultValue: ''
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
